"""initial schema

Revision ID: 4e6994f373f0
Revises: 
Create Date: 2026-08-12 18:39:14.751095
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4e6994f373f0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('timezone', sa.String(length=80), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('week_starts_on', sa.Integer(), nullable=False),
    sa.Column('default_analytics_period', sa.String(length=20), nullable=False),
    sa.Column('location_capture_enabled', sa.Boolean(), nullable=False),
    sa.Column('tailscale_base_url', sa.String(length=500), nullable=True),
    sa.Column('shortcut_token_hash', sa.String(length=64), nullable=True),
    sa.Column('setup_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_settings'))
    )
    op.create_table('categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('icon', sa.String(length=80), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_categories_name'))
    )
    op.create_table('payment_methods',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('issuer', sa.String(length=120), nullable=True),
    sa.Column('last_four', sa.String(length=4), nullable=True),
    sa.Column('method_type', sa.Enum('credit_card', 'debit_card', 'transit_card', 'cash', 'digital_wallet', 'bank_transfer', 'other', name='paymentmethodtype', native_enum=False), nullable=False),
    sa.Column('shortcut_match_text', sa.String(length=180), nullable=True),
    sa.Column('icon', sa.String(length=80), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_methods')),
    sa.UniqueConstraint('shortcut_match_text', name=op.f('uq_payment_methods_shortcut_match_text'))
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('ledger_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_event_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.Enum('expense', 'income', 'refund', 'transfer', 'adjustment', name='transactiontype', native_enum=False), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('merchant_raw', sa.String(length=500), nullable=False),
    sa.Column('merchant_normalized', sa.String(length=240), nullable=False),
    sa.Column('card_raw_name', sa.String(length=240), nullable=True),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('payment_method_id', sa.String(length=36), nullable=True),
    sa.Column('purpose', sa.String(length=240), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('location_name', sa.String(length=240), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('location_source', sa.String(length=40), nullable=True),
    sa.Column('source', sa.Enum('wallet_shortcut', 'manual_pwa', 'csv_import', 'recurring', 'simulator', name='transactionsource', native_enum=False), nullable=False),
    sa.Column('review_status', sa.Enum('confirmed', 'needs_review', 'missing_information', 'duplicate_candidate', name='reviewstatus', native_enum=False), nullable=False),
    sa.Column('is_excluded_from_analytics', sa.Boolean(), nullable=False),
    sa.Column('deduplication_key', sa.String(length=64), nullable=False),
    sa.Column('base_amount_minor', sa.Integer(), nullable=True),
    sa.Column('exchange_rate', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('exchange_rate_source', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_ledger_transactions_category_id_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.id'], name=op.f('fk_ledger_transactions_payment_method_id_payment_methods'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_transactions')),
    sa.UniqueConstraint('client_event_id', name=op.f('uq_ledger_transactions_client_event_id'))
    )
    with op.batch_alter_table('ledger_transactions', schema=None) as batch_op:
        batch_op.create_index('ix_transactions_date', ['transaction_date'], unique=False)
        batch_op.create_index('ix_transactions_dedup', ['deduplication_key', 'transaction_date'], unique=False)
        batch_op.create_index('ix_transactions_merchant', ['merchant_normalized'], unique=False)
        batch_op.create_index('ix_transactions_review', ['review_status'], unique=False)

    op.create_table('merchant_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pattern', sa.String(length=240), nullable=False),
    sa.Column('normalized_pattern', sa.String(length=240), nullable=False),
    sa.Column('match_type', sa.Enum('exact', 'contains', 'regex', name='merchantmatchtype', native_enum=False), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('payment_method_id', sa.String(length=36), nullable=True),
    sa.Column('default_purpose', sa.String(length=240), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_merchant_rules_category_id_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.id'], name=op.f('fk_merchant_rules_payment_method_id_payment_methods'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_merchant_rules'))
    )
    with op.batch_alter_table('merchant_rules', schema=None) as batch_op:
        batch_op.create_index('ix_merchant_rules_enabled_priority', ['is_enabled', 'priority'], unique=False)

    op.create_table('user_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_user_sessions_token_hash'))
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('import_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_event_id', sa.String(length=64), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('result', sa.String(length=60), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.String(length=240), nullable=True),
    sa.Column('transaction_id', sa.String(length=36), nullable=True),
    sa.Column('merchant_summary', sa.String(length=120), nullable=True),
    sa.Column('amount_summary', sa.String(length=40), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('request_identity', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['ledger_transactions.id'], name=op.f('fk_import_events_transaction_id_ledger_transactions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_events'))
    )
    with op.batch_alter_table('import_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_events_client_event_id'), ['client_event_id'], unique=False)
        batch_op.create_index('ix_import_events_received', ['received_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_events', schema=None) as batch_op:
        batch_op.drop_index('ix_import_events_received')
        batch_op.drop_index(batch_op.f('ix_import_events_client_event_id'))

    op.drop_table('import_events')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sessions_user_id'))

    op.drop_table('user_sessions')
    with op.batch_alter_table('merchant_rules', schema=None) as batch_op:
        batch_op.drop_index('ix_merchant_rules_enabled_priority')

    op.drop_table('merchant_rules')
    with op.batch_alter_table('ledger_transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_transactions_review')
        batch_op.drop_index('ix_transactions_merchant')
        batch_op.drop_index('ix_transactions_dedup')
        batch_op.drop_index('ix_transactions_date')

    op.drop_table('ledger_transactions')
    op.drop_table('users')
    op.drop_table('payment_methods')
    op.drop_table('categories')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
